services:
  # The Backend Authentication Service
  auth-service:
    build:
      context: ./auth-service # Path to the backend's build context
      dockerfile: Dockerfile.dev
    container_name: auth-service-dev
    ports:
      - "8000:8000" # Expose to host machine for direct API testing
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    env_file:
      - .env 
    depends_on:
      - mongo

  # The Frontend React App
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: react-app-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    depends_on:
      - auth-service

  # The Question Service
  question-service:
    build:
      context: ./question-service
      dockerfile: dockerfile
    container_name: question-service-dev
    ports:
      - "3013:3013"
    volumes:
      - ./question-service:/app
      - /app/node_modules
    depends_on:
      - mongo
  
  matching-service:
    build:
      context: ./matching-service
      dockerfile: Dockerfile
    container_name: matching-service-dev
    volumes:
      - ./matching-service:/app
      - /app/node_modules
    ports:
      - "3001:3001"   # Express + BullBoard
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis-dev
    ports:
      - "6379:6379"
    command: redis-server --appendonly no --save "" # remove persistence; DB starts fresh upon rerun

  # The Database
  mongo:
    image: mongo:7
    container_name: mongo-auth-dev
    ports:
      - "27017:27017" # Expose to host machine for database tools
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  redis_data:
